# Generated by Django 6.0.3 on 2026-06-29 21:37

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servidores.pessoa')),
                ('matricula', models.CharField(help_text='Matrícula do aluno', max_length=15, unique=True, verbose_name='Matrícula')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, null=True, upload_to='alunos', variations={}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
            bases=('servidores.pessoa',),
        ),
    ]
