# Generated by Django 6.0.3 on 2026-04-10 00:14

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Endereço de e-mail', max_length=100, verbose_name='Email')),
                ('matricula', models.CharField(help_text='Matrícula do servidor', max_length=50, verbose_name='Matrícula')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='alunos', variations={}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
