# Generated by Django 6.0.3 on 2026-05-21 00:19

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="foto",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                null=True,
                upload_to="alunos",
                variations={},
                verbose_name="Foto",
            ),
        ),
    ]
