# Generated by Django 6.0.3 on 2026-05-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_alter_aluno_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="matricula",
            field=models.CharField(
                help_text="Matrícula do aluno",
                max_length=15,
                unique=True,
                verbose_name="Matrícula",
            ),
        ),
    ]
