# Generated by Django 6.0.3 on 2026-04-16 22:47

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do porteiros', max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Email do porteiros', max_length=50, verbose_name='Email')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, help_text='Foto do porteiro', upload_to='porteiros', variations={}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'porteiros',
                'verbose_name_plural': 'Porteiros',
            },
        ),
    ]
