# Generated by Django 6.0.3 on 2026-05-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porteiro',
            name='cpf',
            field=models.CharField(help_text='CPF do porteiro', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='porteiro',
            name='email',
            field=models.EmailField(help_text='Email do porteiros', max_length=50, unique=True, verbose_name='Email'),
        ),
    ]
