# Generated by Django 6.0.3 on 2026-06-12 01:02

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porteiro',
            options={'ordering': [django.db.models.functions.text.Upper('nome')], 'verbose_name': 'porteiros', 'verbose_name_plural': 'Porteiros'},
        ),
    ]
