# Generated by Django 6.0.3 on 2026-06-29 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da sala', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{3,3}$')], verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('Sala de aula', 'Sala de aula'), ('Sala comunitária', 'Sala comunitária')], help_text='Tipo da sala', verbose_name='Tipo')),
                ('anexo', models.CharField(choices=[('CT', 'Prédio Principal - Centro de Tecnologia'), ('A', 'Anexo A - CT'), ('B', 'Anexo B - CT'), ('C', 'Anexo C - CT')], help_text='Anexo da sala', verbose_name='Anexo')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nome'],
            },
        ),
    ]
