# Generated by Django 6.0.3 on 2026-03-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da sala', max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(help_text='Tipo da sala', max_length=100, verbose_name='Tipo')),
                ('Anexo', models.CharField(help_text='Anexo da sala', max_length=100, verbose_name='Anexo')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
