# Generated by Django 6.0.3 on 2026-05-25 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='anexo',
            field=models.CharField(choices=[('CT', 'Prédio Principal - Centro de Tecnologia'), ('A', 'Anexo A - CT'), ('B', 'Anexo B - CT'), ('C', 'Anexo C - CT')], help_text='Anexo da sala', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(help_text='Nome da sala', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{3,3}$')], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('Sala de aula', 'Sala de aula'), ('Sala comunitária', 'Sala comunitária')], help_text='Tipo da sala', verbose_name='Tipo'),
        ),
    ]
