# Generated by Django 6.0.3 on 2026-04-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='Anexo',
            new_name='anexo',
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(help_text='Nome da sala', max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
