# Generated by Django 6.0.3 on 2026-06-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['nome'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
    ]
