# Generated by Django 6.0.3 on 2026-04-02 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_rename_anexo_sala_anexo_alter_sala_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(help_text='Nome da sala', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{3}]+$')], verbose_name='Nome'),
        ),
    ]
