# Generated by Django 6.0.3 on 2026-04-23 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
        migrations.CreateModel(
            name='CopiaChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Status do chave', max_length=100, verbose_name='Status')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaves.chave', verbose_name='Chave')),
            ],
        ),
    ]
