# Generated by Django 6.0.3 on 2026-04-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(help_text='Sala que a chave pertence', max_length=100, verbose_name='Sala')),
                ('quantidadeCopias', models.CharField(help_text='Quantidade de cópias da chave', max_length=5, verbose_name='Quantidade de Cópias')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
    ]
