# Generated by Django 6.0.3 on 2026-06-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadeCopias', models.PositiveIntegerField(default=1, help_text='Quantidade de cópias da chave', verbose_name='Quantidade de Cópias')),
                ('sala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
        migrations.CreateModel(
            name='CopiaChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCopia', models.PositiveIntegerField(default=1, verbose_name='Numero da Cópia')),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('Q', 'Quebrada')], default='D', help_text='Status do chave', max_length=100, verbose_name='Status')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaves.chave', verbose_name='Chave')),
            ],
            options={
                'verbose_name': 'Cópia da Chave',
                'verbose_name_plural': 'Cópias das Chaves',
                'unique_together': {('chave', 'numeroCopia')},
            },
        ),
    ]
