# Generated by Django 6.0.3 on 2026-06-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave',
            options={'ordering': ['sala__nome'], 'verbose_name': 'Chave', 'verbose_name_plural': 'Chaves'},
        ),
    ]
