# Generated by Django 6.0.3 on 2026-05-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copiachave',
            options={'verbose_name': 'Cópia da Chave', 'verbose_name_plural': 'Cópias das Chaves'},
        ),
        migrations.AddField(
            model_name='chave',
            name='quantidadeCopias',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de cópias da chave', verbose_name='Quantidade de Cópias'),
        ),
        migrations.AddField(
            model_name='copiachave',
            name='numeroCopia',
            field=models.PositiveIntegerField(default=1, verbose_name='Numero da Cópia'),
        ),
        migrations.AlterField(
            model_name='copiachave',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('Q', 'Quebrada')], default='D', help_text='Status do chave', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='copiachave',
            unique_together={('chave', 'numeroCopia')},
        ),
    ]
