# Generated by Django 6.0.3 on 2026-04-14 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
        ('salas', '0004_alter_sala_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='quantidadeCopias',
        ),
        migrations.AlterField(
            model_name='chave',
            name='sala',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salas.sala', verbose_name='Sala'),
        ),
        migrations.CreateModel(
            name='CopiaChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Status do chave', max_length=100, verbose_name='Status')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaves.chave', verbose_name='Chave')),
            ],
        ),
    ]
