# Generated by Django 6.0.3 on 2026-05-19 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porteiros', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRetirada', models.DateTimeField(help_text='Data da retirada', verbose_name='Data de Retirada')),
                ('dataDevolucao', models.DateTimeField(help_text='Data da devolução', null=True, verbose_name='Data de Devolução')),
                ('status', models.CharField(choices=[('A', 'Andamento'), ('D', 'Devolvido')], default='A', help_text='Status da Devolução', verbose_name='Status')),
                ('porteiroDevolucao', models.ForeignKey(default=1, help_text='Porteiro que recebeu a chave', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='porteiro_devolucao', to='porteiros.porteiro', verbose_name='Porteiro')),
                ('porteiroEntrega', models.ForeignKey(default=1, help_text='Porteiro que entregou a chave', on_delete=django.db.models.deletion.PROTECT, related_name='porteiro_entrega', to='porteiros.porteiro', verbose_name='Porteiro')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
        migrations.CreateModel(
            name='EmprestimoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_reserva_emprestimo', to='emprestimos.emprestimo', verbose_name='Empréstimo')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_reserva_reserva', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Reserva do Empréstimo',
                'verbose_name_plural': 'Reservas do Empréstimo',
            },
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='reservas',
            field=models.ManyToManyField(related_name='emprestimo_reservas', through='emprestimos.EmprestimoReserva', to='reservas.reserva'),
        ),
    ]
