# Generated by Django 6.0.3 on 2026-04-28 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRetirada', models.DateTimeField(help_text='Data da retirada', verbose_name='Data de Retirada')),
                ('dataDevolucao', models.DateTimeField(help_text='Data da devolução', verbose_name='Data de Devolução')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_emprestimo_emprestimo', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Reserva concluída',
                'verbose_name_plural': 'Reservas concluídas',
            },
        ),
    ]
