# Generated by Django 6.0.3 on 2026-06-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['dataRetirada'], 'verbose_name': 'Emprestimo', 'verbose_name_plural': 'Emprestimos'},
        ),
    ]
