# Generated by Django 6.0.3 on 2026-06-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0002_alter_chave_options'),
        ('emprestimos', '0002_alter_emprestimo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimoreserva',
            name='copia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chaves.copiachave', verbose_name='Cópia Entregue'),
        ),
    ]
