# Generated by Django 6.0.3 on 2026-04-30 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_emprestimo_options_and_more'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestimoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_reserva_emprestimo', to='emprestimos.emprestimo', verbose_name='Empréstimo')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_reserva_reserva', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Reserva do Empréstimo',
                'verbose_name_plural': 'Reservas do Empréstimo',
            },
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='reservas',
            field=models.ManyToManyField(related_name='emprestimo_reservas', through='emprestimos.EmprestimoReserva', to='reservas.reserva'),
        ),
        migrations.DeleteModel(
            name='ReservaEmprestimo',
        ),
    ]
