# Generated by Django 6.0.3 on 2026-05-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_emprestimoreserva_emprestimo_reservas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataDevolucao',
            field=models.DateTimeField(help_text='Data da devolução', null=True, verbose_name='Data de Devolução'),
        ),
    ]
