# Generated by Django 6.0.3 on 2026-05-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0004_alter_emprestimo_datadevolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.BooleanField(default=False, help_text='Status', null=True, verbose_name='Status'),
        ),
    ]
