# Generated by Django 6.0.3 on 2026-05-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0005_emprestimo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(default='D', help_text='Status da Devolução', max_length=1, null=True, verbose_name='Status'),
        ),
    ]
