# Generated by Django 6.0.3 on 2026-05-13 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0006_alter_emprestimo_status'),
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='dataDevolucao',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='status',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='porteiro',
            field=models.ForeignKey(default=1, help_text='Porteiro que entregou a chave', on_delete=django.db.models.deletion.PROTECT, to='porteiros.porteiro', verbose_name='Porteiro'),
        ),
        migrations.CreateModel(
            name='OrdemEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='D', help_text='Status da Devolução', null=True, verbose_name='Status')),
                ('dataDevolucao', models.DateTimeField(help_text='Data da devolução', null=True, verbose_name='Data de Devolução')),
                ('emprestimos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_emprestimos_emprestimo', to='emprestimos.emprestimo', verbose_name='Emprestimo')),
            ],
        ),
    ]
