# Generated by Django 6.0.3 on 2026-05-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0007_remove_emprestimo_datadevolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='dataDevolucao',
            field=models.DateTimeField(help_text='Data da devolução', null=True, verbose_name='Data de Devolução'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(default='D', help_text='Status da Devolução', null=True, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='OrdemEmprestimo',
        ),
    ]
