# Generated by Django 6.0.3 on 2026-05-14 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0008_emprestimo_datadevolucao_emprestimo_status_and_more'),
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='porteiro',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='porteiroDevolucao',
            field=models.ForeignKey(default=1, help_text='Porteiro que recebeu a chave', on_delete=django.db.models.deletion.PROTECT, related_name='porteiro_devolucao', to='porteiros.porteiro', verbose_name='Porteiro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='porteiroEntrega',
            field=models.ForeignKey(default=1, help_text='Porteiro que entregou a chave', on_delete=django.db.models.deletion.PROTECT, related_name='porteiro_entrega', to='porteiros.porteiro', verbose_name='Porteiro'),
        ),
    ]
