# Generated by Django 6.0.3 on 2026-05-14 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0009_remove_emprestimo_porteiro_and_more'),
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='porteiroDevolucao',
            field=models.ForeignKey(default=1, help_text='Porteiro que recebeu a chave', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='porteiro_devolucao', to='porteiros.porteiro', verbose_name='Porteiro'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(default='A', help_text='Status da Devolução', null=True, verbose_name='Status'),
        ),
    ]
