# Generated by Django 6.0.3 on 2026-05-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0010_alter_emprestimo_porteirodevolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('A', 'Andamento'), ('D', 'Devolvido')], default='A', help_text='Status da Devolução', verbose_name='Status'),
        ),
    ]
