# Generated by Django 6.0.3 on 2026-06-29 21:37

import django.db.models.deletion
import django.db.models.functions.text
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Endereço de e-mail', max_length=100, verbose_name='Email')),
                ('bloqueado', models.BooleanField(default=False, help_text='Bloqueio por danos', verbose_name='Bloquado')),
                ('quantidadeDanos', models.IntegerField(default=0, help_text='Contagem de danos', verbose_name='Quantidade de Danos')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servidores.pessoa')),
                ('siape', models.CharField(help_text='Siape do servidor', max_length=7, unique=True, verbose_name='Siape')),
                ('funcao', models.CharField(help_text='Função do Servidor', max_length=100, verbose_name='Função')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, null=True, upload_to='servidores', variations={}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
            bases=('servidores.pessoa',),
        ),
    ]
