# Generated by Django 6.0.3 on 2026-05-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servidores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servidor",
            name="siape",
            field=models.CharField(
                help_text="Siape do servidor",
                max_length=7,
                unique=True,
                verbose_name="Siape",
            ),
        ),
    ]
