# Generated by Django 6.0.3 on 2026-05-21 00:18

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servidores", "0002_alter_servidor_siape"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servidor",
            name="foto",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                null=True,
                upload_to="servidores",
                variations={},
                verbose_name="Foto",
            ),
        ),
    ]
