# Generated by Django 6.0.3 on 2026-06-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0002_alter_servidor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Bloqueio por danos', verbose_name='Bloquado'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='quantidadeDanos',
            field=models.IntegerField(default=0, help_text='Contagem de danos', verbose_name='Quantidade de Danos'),
        ),
    ]
