# Generated by Django 6.0.3 on 2026-04-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chaves', '0001_initial'),
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioReserva', models.DateField(help_text='Data de inicio da reserva', verbose_name='Inicio da Reserva')),
                ('fimReserva', models.DateField(help_text='Data de fim da reserva', verbose_name='Fim da Reserva')),
                ('chave', models.ForeignKey(help_text='Chave que deseja reservar', on_delete=django.db.models.deletion.CASCADE, to='chaves.chave', verbose_name='Chave')),
                ('titular', models.ForeignKey(help_text='Titular da reserva', on_delete=django.db.models.deletion.CASCADE, to='servidores.servidor', verbose_name='Titular')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
