# Generated by Django 6.0.3 on 2026-05-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(default='A', help_text='Status da reserva', max_length=1, verbose_name='Status'),
        ),
    ]
