# Generated by Django 6.0.3 on 2026-05-19 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fimReserva',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 20, 0, 28, 55, 860584, tzinfo=datetime.timezone.utc), help_text='Data de fim da reserva', verbose_name='Fim da Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='inicioReserva',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 19, 22, 28, 55, 860564, tzinfo=datetime.timezone.utc), help_text='Data de inicio da reserva', verbose_name='Inicio da Reserva'),
        ),
    ]
