# Generated by Django 6.0.3 on 2026-05-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_fimreserva_alter_reserva_inicioreserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fimReserva',
            field=models.DateTimeField(help_text='Data de fim da reserva', verbose_name='Fim da Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='inicioReserva',
            field=models.DateTimeField(help_text='Data de inicio da reserva', verbose_name='Inicio da Reserva'),
        ),
    ]
