# Generated by Django 6.0.3 on 2026-05-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('A', 'Agendado'), ('R', 'Realizado'), ('C', 'Cancelado')], default='A', help_text='Status da reserva', max_length=1, verbose_name='Status'),
        ),
    ]
