# Generated by Django 6.0.3 on 2026-05-28 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0002_alter_copiachave_options_chave_quantidadecopias_and_more'),
        ('reservas', '0002_alter_reserva_chave_alter_reserva_titular'),
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='chave',
            field=models.ForeignKey(help_text='Chave que deseja reservar', on_delete=django.db.models.deletion.CASCADE, to='chaves.chave', verbose_name='Chave'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='titular',
            field=models.ForeignKey(help_text='Titular da reserva', on_delete=django.db.models.deletion.CASCADE, to='servidores.servidor', verbose_name='Titular'),
        ),
    ]
